/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sun Jan  9 15:07:08 2000
 */
#ifndef __CEXTRACT__
#if __STDC__

extern double torch_cephes_cabs ( cmplx *z );
extern void torch_cephes_cadd ( cmplx *a, cmplx *b, cmplx *c );
extern double torch_cephes_cay ( double q );
extern void torch_cephes_cdiv ( cmplx *a, cmplx *b, cmplx *c );
extern void torch_cephes_cmov ( short *a, short *b );
extern void torch_cephes_cmul ( cmplx *a, cmplx *b, cmplx *c );
extern void torch_cephes_cneg ( cmplx *a );
extern void torch_cephes_csqrt ( cmplx *z, cmplx *w );
extern void torch_cephes_csub ( cmplx *a, cmplx *b, cmplx *c );
extern double torch_cephes_ellie ( double phi, double m );
extern double torch_cephes_ellik ( double phi, double m );
extern double torch_cephes_ellpe ( double x );
extern int torch_cephes_ellpj ( double u, double m, double *sn, double *cn, double *dn, double *ph );
extern double torch_cephes_ellpk ( double x );
extern int torch_cephes_getnum ( char *line, double *val );
extern int torch_cephes_lampln ( void );
extern int torch_cephes_main ( void );
extern void torch_cephes_mtherr ( char *name, int code );
extern double torch_cephes_p1evl ( double x, double coef[], int N );
extern double torch_cephes_polevl ( double x, double coef[], int N );
extern int torch_cephes_quadf ( double x, double y, int pzflg );
extern double torch_cephes_response ( double f, double amp );
extern int torch_cephes_spln ( void );
extern int torch_cephes_xfun ( void );
extern int torch_cephes_zplna ( void );
extern int torch_cephes_zplnb ( void );
extern int torch_cephes_zplnc ( void );

#else /* __STDC__ */

extern double torch_cephes_cabs (/* cmplx *z */);
extern void torch_cephes_cadd (/* cmplx *a, cmplx *b, cmplx *c */);
extern double torch_cephes_cay (/* double q */);
extern void torch_cephes_cdiv (/* cmplx *a, cmplx *b, cmplx *c */);
extern void torch_cephes_cmov (/* short *a, short *b */);
extern void torch_cephes_cmul (/* cmplx *a, cmplx *b, cmplx *c */);
extern void torch_cephes_cneg (/* cmplx *a */);
extern void torch_cephes_csqrt (/* cmplx *z, cmplx *w */);
extern void torch_cephes_csub (/* cmplx *a, cmplx *b, cmplx *c */);
extern double torch_cephes_ellie (/* double phi, double m */);
extern double torch_cephes_ellik (/* double phi, double m */);
extern double torch_cephes_ellpe (/* double x */);
extern int torch_cephes_ellpj (/* double u, double m, double *sn, double *cn, double *dn, double *ph */);
extern double torch_cephes_ellpk (/* double x */);
extern int torch_cephes_getnum (/* char *line, double *val */);
extern int torch_cephes_lampln (/* void */);
extern int torch_cephes_main (/* void */);
extern void torch_cephes_mtherr (/* char *name, int code */);
extern double torch_cephes_p1evl (/* double x, double coef[], int N */);
extern double torch_cephes_polevl (/* double x, double coef[], int N */);
extern int torch_cephes_quadf (/* double x, double y, int pzflg */);
extern double torch_cephes_response (/* double f, double amp */);
extern int torch_cephes_spln (/* void */);
extern int torch_cephes_xfun (/* void */);
extern int torch_cephes_zplna (/* void */);
extern int torch_cephes_zplnb (/* void */);
extern int torch_cephes_zplnc (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
